[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "next_sparseconvnet"
authors = [{name = "M.Kekic, M.Perez", email = "martinperezmaneiro@gmail.com"}]
dynamic = ["version", "description"]
